#!/usr/bin/env bash

# Arch Linux Fast Install 
# --------------------------------
# author    : Virus_Man
#             
# project   : ArchInst
#             
# license   : LGPL-3.0 (http://opensource.org/licenses/lgpl-3.0.html)
#
# reference : https://wiki.archlinux.org/index.php/Installation_guide

apptitle="Arch Linux Fast Install (archinst) - Version: 2024.02.14.00.00.01 (GPLv3)"
baseurl=https://raw.githubusercontent.com/vt71ru/arch_Install/main/archinst

logo () {
# This will be shown on every set as user is progressing
echo -ne "
__________________________________________________________________________________________________________
|                                                                                                         |
|                                                                                                         |
| █████  ██████   ██████ ██   ██     ██ ███    ██ ███████ ████████  █████  ██      ██      ███████ ██████ |
|██   ██ ██   ██ ██      ██   ██     ██ ████   ██ ██         ██    ██   ██ ██      ██      ██      ██   ██|
|███████ ██████  ██      ███████     ██ ██ ██  ██ ███████    ██    ███████ ██      ██      █████   ██████ |
|██   ██ ██   ██ ██      ██   ██     ██ ██  ██ ██      ██    ██    ██   ██ ██      ██      ██      ██   ██|
|██   ██ ██   ██  ██████ ██   ██     ██ ██   ████ ███████    ██    ██   ██ ███████ ███████ ███████ ██   ██|
|                                                                                                         |
|---------------------------------------------------------------------------------------------------------|
|                Install arch linux in few clicks. Even a 5 year kid can install arch now.                |
|---------------------------------------------------------------------------------------------------------|
|                               Base Installation Of Arch Linux Begins Now                                |
|       Check: https://github.com/vt71ru/arch_install/ To Know More Details About This Installation       |
|---------------------------------------------------------------------------------------------------------|
|_________________________________________________________________________________________________________|

"
}

chose_lang () {
echo "Please select languale for installiation system"
select lang in English Russian Quit;
do
  case $lang in
  "English")
     
     ;;
  "Russian")
     source  ./lang/russian
     choose_lang
     ;;
  "Quit")
     break
     ;;
  esac
done
}

wificonn () {
echo  -e "Check internet connection"........
up=`ping -c 1 -q raw.githubusercontent.com`
case $? in
0) echo -en "+ \033[32;1;49mInternet is available \033[0m\n"
  echo -e "Connection aviable..."
	;;
*) echo -en "- \033[31;1;49mWarning! \033[0m\033[31;1;5mInternet not available \033[0m\n"
select conntype in Cable Wireless
do
  case $conntype in
  "Cable")
     echo "I also use $conntype connection. Check cable connection"
     ;;
  "Wifi")
     iwctl --passphrase passphrase station device connect SSID
     ;;
  esac
done
esac
}

init () {
sleep 3s
#wificonn
echo "Привет сосед"
echo "Updating Keyrings"
sleep 2s
pacman -Sy --needed --noconfirm archlinux-keyring
clear
echo "Ensuring if the system clock is accurate."
timedatectl set-ntp true
sleep 3s
clear

}

genfstab (){
echo "generating fstab file"
genfstab -U /mnt >> /mnt/etc/fstab
sleep 2s
clear
}

logo
chose_lang
init
genfstab
clear
