#!/usr/bin/env bash

#######################################################################
#                   Arch Linux Fast Install                           #  
# --------------------------------------------------------------------#
# author    : Virus_Man                                               # 
#                                                                     #
# project   : ArchInst                                                # 
#                                                                     #
# license   : LGPL-3.0 (http://opensource.org/licenses/lgpl-3.0.html) #
#                                                                     #
# reference : https://wiki.archlinux.org/index.php/Installation_guide #
#######################################################################

logo () {
# This will be shown on every set as user is progressing
echo -ne "
__________________________________________________________________________________________________________
|                                                                                                         |
|                                                                                                         |
| █████  ██████   ██████ ██   ██     ██ ███    ██ ███████ ████████  █████  ██      ██      ███████ ██████ |
|██   ██ ██   ██ ██      ██   ██     ██ ████   ██ ██         ██    ██   ██ ██      ██      ██      ██   ██|
|███████ ██████  ██      ███████     ██ ██ ██  ██ ███████    ██    ███████ ██      ██      █████   ██████ |
|██   ██ ██   ██ ██      ██   ██     ██ ██  ██ ██      ██    ██    ██   ██ ██      ██      ██      ██   ██|
|██   ██ ██   ██  ██████ ██   ██     ██ ██   ████ ███████    ██    ██   ██ ███████ ███████ ███████ ██   ██|
|                                                                                                         |
|---------------------------------------------------------------------------------------------------------|
|                Install arch linux in few clicks. Even a 5 year kid can install arch now.                |
|---------------------------------------------------------------------------------------------------------|
|                               Base Installation Of Arch Linux Begins Now                                |
|       Check: https://github.com/vt71ru/arch_install/ To Know More Details About This Installation       |
|---------------------------------------------------------------------------------------------------------|
|_________________________________________________________________________________________________________|

"
}

init() {
echo "Please select languale for installiation system"
select lang in English Russian German Quit;
do
  case $lang in
  "English")
     
     ;;
  "Russian")
     source  ./lang/russian
     choose_lang
     ;;
  "German")
     source  ./lang/german
     choose_lang
     ;;
  "Quit")
     break
     ;;
  esac
done

ColorOff=$'\e[0m';
Green=$'\e[0;32m';
Yellow=$'\e[0;33m';
Red=$'\e[0;31m';

cpu_type=$(lscpu | grep "Model name:" | cut -c 22-)
cpu_cores=$(lscpu | grep "^CPU(s):" | cut -c 22-)

if (lscpu | grep "CPU max MHz" &> /dev/null) then
    cpu_freq=$(lscpu | grep "CPU max MHz:" | cut -c 22-)
else
    cpu_freq=$(lscpu | grep "CPU MHz:" | cut -c 22-)
fi

mem_total=$(free -m | awk 'NR==2 {print $2}')
mem_used=$(free -m | awk 'NR==2 {print $3}')
gpu_cpu=$(lspci | grep VGA | cut -c 36- | awk 'NR==1')
gpu_dedicated=$(lspci | grep VGA | cut -c 36- | awk 'NR==2')
block_dev=$(echo -e "${Yellow}Block Devices: \n${Green}$(lsblk | grep "sd." | awk '{print "'${Red}'> '${Green}'"$1" '${Yellow}'Type: '${Green}'"$6" '${Yellow}'Size: '${Green}'"$4" '${Green}'"$7}' | column -t | sed 's/>/    >/')")


echo "  ${Red}|${Red}$(whoami)${Green}@${Yellow}$(</etc/hostname) ${Red}------------------------------------------------>"
echo "  ${Red}|${Yellow}System Uptime: ${Green}$(uptime -p)"
echo "  ${Red}|${Yellow}Kernel Version: ${Green}$kversion"
echo "  ${Red}|${Yellow}Command Shell: ${Green}$shell"
echo "  ${Red}|${Yellow}CPU Model: ${Green}$cpu_type"
echo "  ${Red}|${Yellow}CPU Cores: ${Green}$cpu_cores"
echo "  ${Red}|${Yellow}CPU Clock: ${Green}$cpu_freq MHz"
echo "  ${Red}|${Yellow}GPU - CPU: ${Green}$gpu_cpu"
echo "  ${Red}|${Yellow}GPU - dedicated: ${Green}$gpu_dedicated"
echo "  ${Red}|${Yellow}Memory: ${Green}$mem_used MiB / $mem_total MiB"
echo "  ${Red}|$block_dev"

}

#wificonn () {
#echo  -e "Check internet connection"........
#up=`ping -c 1 -q raw.githubusercontent.com`
#case $? in
#0) echo -en "+ \033[32;1;49mInternet is available \033[0m\n"
#  echo -e "Connection aviable..."
#	;;
#*) echo -en "- \033[31;1;49mWarning! \033[0m\033[31;1;5mInternet not available \033[0m\n"
#select conntype in Cable Wireless
#do
#  case $conntype in
#  "Cable")
#     echo "I also use $conntype connection. Check cable connection"
#     ;;
#  "Wifi")
#     iwctl --passphrase passphrase station device connect SSID
#     ;;
#  esac
#done
#esac
#}


disk () {
              printf " \033[1m ${red} msg1 \n \033[0m"
	      lsblk |grep -v "loop*" |grep -v "arch_root*"
	      printf " \033[1m \n ${white} $msg2:${red} i.e. ${white}/dev/sda \n \033[0m "
	      #printf " \033[1m ${red} WARNING:${green} /dev/sda ${white}may not be empty on your system\n \033[0m "
	      printf " \033[1m \n ${yellow} $msg4 ${white}\033[0m "
	      read yourdrive
	      echo $yourdrive
	      printf " \033[1m ${white} \n $msg5 ${green} cfdisk ${white} $msg7 ${green} fdisk ? \n \033[0m"
	      printf " \033[1m \n ${yellow} $msg6 ${white}\033[0m"
	      read toolchoice
	      if [ "$toolchoice" == cfdisk -o "$toolchoice" == CFDISK ]
		    then
		    cfdisk $yourdrive
	      else
		    fdisk $yourdrive
	      fi
}

genfstab (){
echo "generating fstab file"
genfstab -U /mnt >> /mnt/etc/fstab
sleep 2s
clear
}

logo
init
device_list=$(lsblk -no NAME,SIZE,TYPE,FSTYPE | egrep -v "$USB|loop[0-9]+|sr[0-9]+|fd[0-9]+" | sed 's/[^[:alnum:]_., -]//g' | column -t | sort -k 1,1 | uniq)
device_count=$(<<<"$device_list" wc -l)
echo $device_list
echo $device_count
#disk
#genfstab

