#!/usr/bin/env bash

# Arch Linux Fast Install 
# --------------------------------
# author    : Virus_Man
#             
# project   : ArchInst
#             
# license   : LGPL-3.0 (http://opensource.org/licenses/lgpl-3.0.html)
#
# reference : https://wiki.archlinux.org/index.php/Installation_guide

apptitle="Arch Linux Fast Install (archinst) - Version: 2024.02.14.00.00.01 (GPLv3)"
baseurl=https://raw.githubusercontent.com/vt71ru/arch_Install/main/archinst

logo () {
# This will be shown on every set as user is progressing
echo -ne "
__________________________________________________________________________________________________________
|                                                                                                         |
|                                                                                                         |
| █████  ██████   ██████ ██   ██     ██ ███    ██ ███████ ████████  █████  ██      ██      ███████ ██████ |
|██   ██ ██   ██ ██      ██   ██     ██ ████   ██ ██         ██    ██   ██ ██      ██      ██      ██   ██|
|███████ ██████  ██      ███████     ██ ██ ██  ██ ███████    ██    ███████ ██      ██      █████   ██████ |
|██   ██ ██   ██ ██      ██   ██     ██ ██  ██ ██      ██    ██    ██   ██ ██      ██      ██      ██   ██|
|██   ██ ██   ██  ██████ ██   ██     ██ ██   ████ ███████    ██    ██   ██ ███████ ███████ ███████ ██   ██|
|                                                                                                         |
|---------------------------------------------------------------------------------------------------------|
|                Install arch linux in few clicks. Even a 5 year kid can install arch now.                |
|---------------------------------------------------------------------------------------------------------|
|                               Base Installation Of Arch Linux Begins Now                                |
|       Check: https://github.com/vt71ru/arch_install/ To Know More Details About This Installation       |
|---------------------------------------------------------------------------------------------------------|
|_________________________________________________________________________________________________________|

"
}

init () {
sleep 3s
echo "Internet Connection is a must to begin."
echo "Updating Keyrings"
sleep 2s
pacman -Sy --needed --noconfirm archlinux-keyring
clear
echo "Ensuring if the system clock is accurate."
timedatectl set-ntp true
sleep 3s
clear

# Ставим русскую раскладку
echo "Setting keyboard layout..."
loadkeys ru

# Добавим в консоль шрифт, поддерживающий кириллицу
echo "Setting cyrillic font..."
setfont ter-k20b

#Добавляем русскую локаль
sed -i 's/#ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen
export LANG=ru_RU.UTF-8
}

genfstab (){
echo "generating fstab file"
genfstab -U /mnt >> /mnt/etc/fstab
sleep 2s
clear
}

logo
clear
genfstab
clear
